// src/utils/zonePolygonManager.js
// Pure JS utility — no React imports.
import { frameBounds } from './frameBounds.js';

export function getZoneStyle(color = '#C1121F', isSelected = false) {
  const c = color || '#C1121F';
  return {
    color:       c,
    fillColor:   c,
    fillOpacity: isSelected ? 0.40 : 0.18,
    weight:      isSelected ? 3 : 2,
  };
}

const HOVER_FILL_OPACITY = 0.32;

// ── Per-device color palette ──────────────────────────────────────────────────
// 12 vivid, high-contrast colors visible on both light and dark map tiles
const DEVICE_PALETTE = [
  '#2563eb', // bold blue
  '#059669', // strong emerald
  '#d97706', // deep amber
  '#7c3aed', // vivid violet
  '#dc2626', // strong red
  '#0891b2', // deep cyan
  '#ea580c', // vivid orange
  '#c026d3', // strong fuchsia
  '#16a34a', // vivid green
  '#ca8a04', // rich yellow-gold
  '#4f46e5', // deep indigo
  '#db2777', // vivid pink
];

/**
 * Given a stable device serial number, return a consistent color from the palette.
 * Uses a simple djb2-style hash so the same sn always maps to the same color.
 *
 * NOTE: hashing gives stability but NOT uniqueness — two serials can collide on
 * the same palette entry. When you are colouring a known set of devices that must
 * be told apart on one map, use buildDeviceColorMap() instead.
 */
export function deviceColor(sn) {
  let hash = 5381;
  for (let i = 0; i < sn.length; i++) {
    hash = ((hash << 5) + hash) ^ sn.charCodeAt(i);
    hash = hash >>> 0; // keep unsigned 32-bit
  }
  return DEVICE_PALETTE[hash % DEVICE_PALETTE.length];
}

function hslToHex(h, s, l) {
  const a = (s / 100) * Math.min(l / 100, 1 - l / 100);
  const f = (n) => {
    const k = (n + h / 30) % 12;
    const v = l / 100 - a * Math.max(-1, Math.min(k - 3, Math.min(9 - k, 1)));
    return Math.round(255 * v).toString(16).padStart(2, '0');
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

/**
 * Assign every serial in `sns` a colour that is distinct from all the others.
 *
 * The first 12 devices take the hand-picked palette; past that, colours are
 * generated by walking the hue circle in golden-angle steps so consecutive
 * devices stay far apart in hue. Serials are sorted first, so a given set of
 * devices always produces the same mapping regardless of fetch order.
 *
 * @param {string[]} sns
 * @returns {Record<string, string>} sn -> hex colour
 */
export function buildDeviceColorMap(sns) {
  const unique = [...new Set((sns || []).filter(Boolean).map(String))].sort();
  const map = {};
  unique.forEach((sn, i) => {
    map[sn] = i < DEVICE_PALETTE.length
      ? DEVICE_PALETTE[i]
      : hslToHex(Math.round((i * 137.508) % 360), 72, 52);
  });
  return map;
}

/**
 * Ray-casting point-in-polygon test.
 * @param {number} lat
 * @param {number} lng
 * @param {Array<{lat: number, lng: number}>} polygon
 * @returns {boolean}
 */
export function pointInPolygon(lat, lng, polygon) {
  if (!polygon || polygon.length === 0) return false;
  const n = polygon.length;
  let inside = false;
  let j = n - 1;
  for (let i = 0; i < n; i++) {
    const xi = polygon[i].lng;
    const yi = polygon[i].lat;
    const xj = polygon[j].lng;
    const yj = polygon[j].lat;
    if ((yi > lat) !== (yj > lat)) {
      if (lng < (xj - xi) * (lat - yi) / (yj - yi) + xi) {
        inside = !inside;
      }
    }
    j = i;
  }
  return inside;
}

/**
 * Multi-polygon point test — true if inside any of the sub-polygons.
 * @param {number} lat
 * @param {number} lng
 * @param {Array<Array<{lat: number, lng: number}>>} polygons
 * @returns {boolean}
 */
export function pointInMultiPolygon(lat, lng, polygons) {
  if (!polygons || polygons.length === 0) return false;
  return polygons.some((poly) => pointInPolygon(lat, lng, poly));
}

function _fmt(ts) {
  if (!ts) return null;
  try {
    const d = new Date(ts);
    if (isNaN(d)) return null;
    return d.toLocaleString(undefined, {
      month: 'short', day: '2-digit',
      hour: '2-digit', minute: '2-digit', hour12: false,
    });
  } catch { return null; }
}

export function createPolygonManager(map) {
  // Map<zoneId, { polygon, zone }>
  const _polygons = new Map();
  // Dot markers for the currently selected zone (cleared when zone changes)
  let _dotLayers = [];
  // Per-device playback dots — separate layer group so they don't clobber _dotLayers
  let _deviceDotLayers = [];
  let _selectedZoneId = null;

  function _baseOpacityFor(zoneId) {
    return zoneId === _selectedZoneId ? 0.40 : 0.18;
  }

  // ── Dot rendering (original — visit points from zone data) ────────────────
  function _clearDots() {
    _dotLayers.forEach((m) => { try { map.removeLayer(m); } catch {} });
    _dotLayers = [];
  }

  function _renderDots(zone) {
    _clearDots();
    if (!zone.points || zone.points.length === 0) return;
    const dotColor = zone.color || '#C1121F';

    zone.points.forEach((pt) => {
      const marker = window.L.circleMarker([pt.lat, pt.lng], {
        radius:      4,
        color:       '#fff',
        fillColor:   dotColor,
        fillOpacity: 0.85,
        weight:      1,
      });
      marker.addTo(map);

      const label = _fmt(pt.timestamp);
      if (label) {
        marker.bindTooltip(label, { sticky: true, className: 'fp-dot-tip' });
      }

      _dotLayers.push(marker);
    });
  }

  // ── Device playback dot rendering (NEW) ───────────────────────────────────

  /**
   * Clear all per-device playback dots from the map.
   * Called automatically on zone switch or manually.
   */
  function clearDeviceDots() {
    _deviceDotLayers.forEach((m) => { try { map.removeLayer(m); } catch {} });
    _deviceDotLayers = [];
  }

  /**
   * Render GPS playback points for multiple devices on the map.
   *
   * @param {Array<{ sn: string, user_name: string, color?: string, insidePoints, outsidePoints }>} deviceTracks
   *   Each element is one device's worth of GPS points, split into inside/outside arrays.
   *   `color` is the caller-assigned distinct colour; falls back to the hashed one.
   * @param {Array<{lat, lng}>} polygon - Zone polygon for determining point containment
   */
  function renderDeviceDots(deviceTracks, polygon) {
    clearDeviceDots();
    if (!deviceTracks || deviceTracks.length === 0) return;

    deviceTracks.forEach(({ sn, user_name, color: assignedColor, insidePoints, outsidePoints }) => {
      const color = assignedColor || deviceColor(sn);
      const grey = '#6b7280';

      // Render inside points with device color
      if (insidePoints && insidePoints.length > 0) {
        insidePoints.forEach((pt, idx) => {
          const isFirst = idx === 0;
          const isLast  = idx === insidePoints.length - 1;
          const radius = isFirst || isLast ? 6 : 3.5;

          const marker = window.L.circleMarker([pt.lat, pt.lng], {
            radius,
            color:       '#000',
            fillColor:   color,
            fillOpacity: isFirst || isLast ? 1 : 0.75,
            weight:      isFirst || isLast ? 1.5 : 0.8,
          });

          marker.addTo(map);

          const ts    = _fmt(pt.timestamp);
          const badge = isFirst ? ' · ▶ first' : isLast ? ' · ⬛ last' : '';
          const label = `${user_name || sn}${ts ? `\n${ts}` : ''}${badge}`;
          marker.bindTooltip(label, { sticky: true, className: 'fp-dot-tip' });

          _deviceDotLayers.push(marker);
        });
      }

      // Render outside points in grey
      if (outsidePoints && outsidePoints.length > 0) {
        outsidePoints.forEach((pt) => {
          const marker = window.L.circleMarker([pt.lat, pt.lng], {
            radius: 3,
            color:       '#000',
            fillColor:   grey,
            fillOpacity: 0.5,
            weight:      0.5,
          });

          marker.addTo(map);

          const ts = _fmt(pt.timestamp);
          const label = `${user_name || sn}${ts ? `\n${ts}` : ''} · outside`;
          marker.bindTooltip(label, { sticky: true, className: 'fp-dot-tip' });

          _deviceDotLayers.push(marker);
        });
      }
    });
  }

  // ── Public: renderZones ────────────────────────────────────────────────────
  function renderZones(zones, { onZoneClick, onZoneHover, onZoneHoverOut } = {}) {
    clearAll();
    if (!zones || zones.length === 0) return;

    const allLatLngs = [];

    zones.forEach((zone) => {
      // Multi-polygon zone (e.g. uc_216): pass all rings as a Leaflet multi-polygon
      const isMulti = Array.isArray(zone.polygons) && zone.polygons.length > 0;
      if (!isMulti && (!zone.polygon || zone.polygon.length === 0)) return;

      let latLngs;
      if (isMulti) {
        latLngs = zone.polygons.map((ring) => ring.map(({ lat, lng }) => [lat, lng]));
        latLngs.flat().forEach((ll) => allLatLngs.push(ll));
      } else {
        latLngs = zone.polygon.map(({ lat, lng }) => [lat, lng]);
        allLatLngs.push(...latLngs);
      }

      const zoneColor = zone.color || '#C1121F';
      const isSelected = zone.zone_id === _selectedZoneId;
      const defaultStyle = getZoneStyle(zoneColor, false);
      const selectedStyle = getZoneStyle(zoneColor, true);

      const polygon = window.L.polygon(latLngs, { ...(isSelected ? selectedStyle : defaultStyle) });
      polygon.addTo(map);

      polygon.on('click', () => {
        if (onZoneClick) onZoneClick(zone.zone_id);
      });

      polygon.on('mouseover', () => {
        polygon.setStyle({ fillOpacity: 0.32 });
        if (onZoneHover) onZoneHover(zone.zone_id);
      });

      polygon.on('mouseout', () => {
        polygon.setStyle({ fillOpacity: _baseOpacityFor(zone.zone_id) });
        if (onZoneHoverOut) onZoneHoverOut(zone.zone_id);
      });

      _polygons.set(zone.zone_id, { polygon, zone, defaultStyle, selectedStyle, zoneColor });
    });

    if (allLatLngs.length > 0) {
      try {
        if (zones.length === 1 && zones[0].center) {
          map.setView([zones[0].center.lat, zones[0].center.lng], 14);
        } else {
          const bounds = window.L.latLngBounds(allLatLngs);
          if (bounds.isValid()) frameBounds(map, bounds, { padding: [48, 48] });
        }
      } catch (e) {
        console.warn('[ZonePolygonManager] fitAll failed:', e);
      }
    }
  }

  // ── Public: selectZone ────────────────────────────────────────────────────
  function selectZone(zoneId) {
    _selectedZoneId = zoneId;

    // Restyle all polygons preserving their individual color
    _polygons.forEach(({ polygon, defaultStyle, selectedStyle }, id) => {
      polygon.setStyle(id === zoneId ? selectedStyle : defaultStyle);
    });

    // Clear previous zone visit-dots AND device playback dots on zone switch
    _clearDots();
    clearDeviceDots();

    if (zoneId && _polygons.has(zoneId)) {
      const { polygon, zone } = _polygons.get(zoneId);

      try {
        const bounds = polygon.getBounds();
        if (bounds && bounds.isValid()) {
          frameBounds(map, bounds, { padding: [60, 60], maxZoom: 16 });
        }
      } catch (e) {
        console.warn('[ZonePolygonManager] selectZone fitBounds failed:', e);
      }

      if (!zone.polygons) _renderDots(zone);
    }
  }

  // ── Public: clearAll ──────────────────────────────────────────────────────
  function clearAll() {
    _clearDots();
    clearDeviceDots();
    _polygons.forEach(({ polygon }) => {
      try { map.removeLayer(polygon); } catch {}
    });
    _polygons.clear();
    _selectedZoneId = null;
  }

  return { renderZones, selectZone, clearAll, renderDeviceDots, clearDeviceDots };
}